services:
  python:
    build: ./python
    env_file:
      - .env
    image: bitcoin_quant:latest      # 独自イメージ名にしよ
    container_name: bitcoin_quant
    working_dir: /usr/src/app          # ここ基準にあわせる
    volumes:
      - ./python:/usr/src/app
    ports:
      - "8001:8000"
    tty: true
    stdin_open: true
    command: tail -f /dev/null
